name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: |
            dogosinfo/rotten-potatoes:latest
            dogosinfo/rotten-potatoes:v${{github.run_number}}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG}}

      - name: Deploy to kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          images: dogosinfo/rotten-potatoes:v${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
